name: actions-test
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      userName:
        description: "Username"
        required: true
        default: "Diablo"

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - run: echo "Username: ${{ github.event.inputs.username }}"
      - run: echo "Actor's username: ${{ github.actor }}"
